### ISSUE TITLE
Any tool to install SSL to /system/etc/security/cacerts ?

### ISSUE THREAD

**Issue by marataziat** [anbox/anbox#1097]
anbox.shell can't write anything to  /system/etc/security/cacerts how to make  /system/etc/security/cacerts  writable? I want to put there my own CA

**Comment by baptx** [comment]
Did you find a solution? I have the same problem:
`x86_64:/sdcard/Download # mv mitmproxy.pem /system/etc/security/cacerts/                                                                                                                     
mv: /system/etc/security/cacerts//mitmproxy.pem: Read-only file system`

**Comment by marataziat** [comment]
I have installed android avd and using android sdk :) Now I'm using avd

**Comment by marataziat** [comment]
Use this guide: https://youtube.com/watch?v=NOQikgr_Zjc
But you need to install some gtk packages using apt, i cant it now because im using tablet

**Comment by baptx** [comment]
Thanks, I already used Android AVD but would have preferred Anbox since it is open source and with better performance since it is not using an emulator. The other open source but emulated solution I use is Android X86 in VirtualBox.

**Comment by awaken1ng** [comment]
You can use rootfs overlay to add files, [you'll need to run container manager with `--use-rootfs-overlay` option](https://docs.anbox.io/userguide/advanced/rootfs_overlay.html) (though for some reason, nearly every application started crashing even with empty overlay for me)

Another option is to take the Anbox Android image and repackage it with `unsquashfs` and `mksquashfs`
For reference, Anbox is packing it's image here:
https://github.com/anbox/anbox/blob/2e964bd13279a28556f91273938951b26346b2aa/scripts/create-package.sh#L32

**Comment by baptx** [comment]
@awaken1ng I tried your rootfs solution now but I get the error "Read-only file system":
```
sudo snap run --shell anbox.container-manager
cp mitmproxy.pem /var/snap/anbox/common/combined-rootfs/system/etc/security/cacerts/
cp: cannot create regular file '/var/snap/anbox/common/combined-rootfs/system/etc/security/cacerts/mitmproxy.pem': Read-only file system
```
Do you know how to fix it?

**Comment by baptx** [comment]
@awaken1ng I tried your rootfs overlay solution now and I can confirm that it works, thanks!
I read that it could also work by adding the CA certificate in `/data/misc/keychain/certs-added` instead of `/system/etc/security/cacerts/` (rootfs overlay would not be needed then but I did not get it working).
I tested with the default browser "WebView" and was able to see HTTPS requests with mitmproxy.
Note that I had to rename by mitmproxy.pem file to the name given by this command and add ".0" at the end of the filename:
`openssl x509 -inform PEM -subject_hash_old -in mitmproxy.pem | head -1`
Maybe you had some applications using certificate pinning so this could be the reason you had applications crashing. To bypass certificate pinning, you can use a tool like Frida.
