### ISSUE TITLE
Window titles, Window manager titles

### ISSUE THREAD

**Issue by jidanni** [anbox/anbox#1161]
Here we observe several issues.

1. FOR WINDOW MANAGER TABS (bottom of screenshot): Clock (blue) has a proper window Title, Anbox Application Manager does not, thus its title gets badly crammed and cut off in the tab at the bottom of the screen.

2. FOR TITLES AT TOP OF WINDOWS: Clock is missing its Title, Anbox Application Manager is OK.

3. Clock has a normal sized title block, Anbox Application Manager has a oddly double sized title block.

![18724-3](https://user-images.githubusercontent.com/1230959/59142575-0aa2a400-89f3-11e9-8e77-320272f633fa.jpg)  (Seen on Debian.)

**Comment by JasMich** [comment]
That's not a bug of Anbox:

The clock app doesn't contain an [App Bar](https://material.io/design/components/app-bars-top.html). That's why no title is displayed. In Android freeform mode, the windows manager doesn't add a title to the windows. For adding this, you'll need something as [Floating Apps](https://www.floatingapps.net/). @morphis This feature would be very interesting to implement.

And the Appmrr's Title seems "double sized" just because the designer ***is*** using an App Bar.
