### ISSUE TITLE
Title bar disappearing, causing app usage issues

### ISSUE THREAD

**Issue by danperks** [anbox/anbox#1184]
I'm having an issue with a spesific app, where the top title bar disappears when I click near the top of the screen. I then have to wiggle the window to get the top bar to render again. When this happens, a black bar appears at the bottom, the same size as the title bar. Additionally, all the buttons of the title bar still work when it isn't visisble. This isn't a new issue as it was first reported on issue #928. If log files are the likes are needed, they can be found there.

Here's what it should look like:
![image](https://user-images.githubusercontent.com/49082234/60719102-8a525e80-9f1e-11e9-86bb-25fbb8e47953.png)
Here's what happens when affected:
![image](https://user-images.githubusercontent.com/49082234/60719088-7eff3300-9f1e-11e9-810a-c8fb6dadf32a.png)

**Comment by danperks** [comment]
Update: Just found another issue which sounds to be experiencing the same problem at #1183

**Comment by FranchuFranchu** [comment]
In my case, this caused all mouse clicks to be offset down by the height of the title bar. Another workaround to make the title bar appear again was open any in-app link to make the WebView app open, and then press Escape to get back to the main application.

**Comment by DaMatrix** [comment]
this is an issue with every fullscreen app i've tried so far. is there a way to prevent apps from rendering over the title bar? (or automatically open and then close webview every time an app goes fullscreen :P)

**Comment by zaeima** [comment]
I am also having this exact issue. It seems that when a full screen app is launched, the entire screen is moved up and the title bar is covered, but the title bar's touch inputs still overrides the full screen application's touch input. If I click at the very top right corner of the application's window, it still closes the window. 

The main problem is that I am unable to click any elements at the top of the full screen's application, since the title bar catches all touch inputs I try to put in that area. If I try to move the screen in the full screen app, the screen gets moved down, and the title bar is displayed again, but like @FranchuFranchu said, every single touch input is now offset downwards, essentially making it so that you are still unable to touch any elements at the top edge of the screen.

**Comment by MJFalahi** [comment]
I have same issue , when i run an application , each full screen layout covers the title bar .
![Screenshot from 2020-01-20 11-13-08](https://user-images.githubusercontent.com/29582887/72708642-6c75df80-3b78-11ea-9ce2-2b8780f4454e.png)
![Screenshot from 2020-01-20 11-13-45](https://user-images.githubusercontent.com/29582887/72708662-77c90b00-3b78-11ea-83ca-bedebc538946.png)

when i want to click on "تایید" button , the window closes, because hidden button clicks.

**Comment by pingplug** [comment]
I use single window mode to disable title bar
```
anbox session-manager --single-window --window-size=1920,1080
```
but you can't resize window and can't run multiple window at the same time (I just play one game so it's fine for me)
with #1352 you can get better experience with single window mode
