### ISSUE TITLE
i386, and it does not install.

### ISSUE THREAD

**Issue by cube-mentore** [anbox/anbox#1208]
**Please describe your problem:**
So, I am trying to install anbox onto my Lenovo ThinkPad T61p powered by Linux Mint 19.1. And while I am trying to sudo snap install --devmode --beta anbox, it says
error: snap "anbox" is not available on beta for this architecture
              (i386) but exists on other architectures (amd64).

**What were you expecting?:**
I expected that this snap would work on my pc as wine does.

**Additional info:**
nope.

**Comment by flutterbrony** [comment]
They'll don't support i386 architectures sadly, but I'm working on it, and
successfully build anbox for i386, and use it with Android x86, i'm
thinking of packaging it in a .deb and .rpm files maybe. I just have to
work a bit more on it because the network isn't working

Le mar. 30 juil. 2019 à 07:52, cube-mentore <notifications@github.com> a
écrit :

**Comment by morphis** [comment]
We don't support i386 or do we build Android of i386. Please us a 64-bit system.
