### ISSUE TITLE
EGL_PLATFORM is not autodetected

### ISSUE THREAD

**Issue by okias** [anbox/anbox#1260]
```
# anbox session-manager
libEGL debug: Native platform type: x11 (build-time configuration)
```
even when running on Wayland enabled system.

for example, for small test demo I compiled it's Wayland auto detected at runtime.
```
$  EGL_LOG_LEVEL="debug" ./wayland-egl 
libEGL debug: Native platform type: wayland (autodetected)
```

Didn't found way, how to do it in anbox code yet, since by default in Gentoo distribution, there is surfaceless backend selected (just because in mesa compilation time it's first argument in list of backends) , which of course fails all test and it's unable to initialize anbox surface.

**Comment by shiznix** [comment]
Guessing maybe it can't be done in Anbox because 'anbox session-manager' doesn't actually render an EGL display, that gets done with 'anbox launch'.

Mesa's EGL detection can't query a display that isn't there so it always falls back to use the first entry in Mesa's build-time '-Dplatforms=...' backend order list.

In my case with Gentoo's >=mesa-19.2:
``libEGL debug: Native platform type: surfaceless (build-time configuration)``

**Comment by okias** [comment]
I assume still valid.

**Comment by Fuseteam** [comment]
this should make anbox launch properly
```
mkdir -p ~/.config/systemd/user
wget -O ~/.config/systemd/user/anbox-session-manager.service https://raw.githubusercontent.com/Fuseteam/systemd-service-files/main/user/anbox-session-manager.service
systemctl --user enable --now anbox-session-manager
```
check status with
```
systemctl --user status anbox-session-manager
```
if the status is a green `active (running)` launch anbox from the desktop menu, it should just work
