### ISSUE TITLE
when i try to add repository "ppa:morphis/anbox-support" to  install kernal module for anbox than ierror occurs that your repository don't have the release file 

### ISSUE THREAD

**Issue by ahmedsaeedd1998** [anbox/anbox#1289]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by robinhood2014** [comment]
`sudo add-apt-repository ppa:morphis/anbox-support`
returns:
`...
Err:9 http://ppa.launchpad.net/morphis/anbox-support/ubuntu eoan Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`
Expected:
`Get:9 http://ppa.launchpad.net/morphis/anbox-support/ubuntu eoan Release`
so that I could follow it up with `sudo apt update && sudo apt install anbox-modules-dkms`.

**Comment by roydenyates** [comment]
There is nothing in that ppa for eoan - use disco

**Comment by JamesSwift** [comment]
As far as I can tell the reason they haven't added eoan (19.10) is because the `ashmem` and `binder` modules are now built directly into the kernel. You can skip adding the repository step.

**Comment by roydenyates** [comment]
Yes, just so. Was not clear to me then.

**Comment by Anhad-source** [comment]
do you have the anbox-container.socket in the /run folder?

**Comment by tomchiverton** [comment]
https://docs.anbox.io/userguide/install_kernel_modules.html should surely be updated to say when to skip this step ?

**Comment by Fuseteam** [comment]
@tomchiverton it does: https://docs.anbox.io/userguide/install_kernel_modules.html#install-dkms-package-from-ppa
![2021-11-16-104630_724x149_scrot](https://user-images.githubusercontent.com/10421851/141996879-1b8aed72-a71b-4da6-b334-baae93852f27.png)
people just don't read

**Comment by kapitannwel** [comment]
just go straight on installing the package like so:

`sudo apt install anbox`
