### ISSUE TITLE
Why anbox doesn't have a normal windows bar  ?

### ISSUE THREAD

**Issue by RomanJos** [anbox/anbox#1308]
Hi, I just wanted to know why anbox didn't have a normal title bar with resize, minimise etc from the DE ? Is this by design ? Why ? Also the border to resize the window are too much bigger I can't click on certain button sometimes and its really frustrating

**Comment by alxlg** [comment]
https://github.com/anbox/anbox/issues/961

**Comment by morphis** [comment]
We can add a configuration option to the snap which allows you enable or disable the Android window bar.

**Comment by RomanJos** [comment]
I don't use snap but yeah if we can choose in the settings it would be cool !

**Comment by alxlg** [comment]
@morphis do you mean what I asked in #961, option for server-side decorations?

**Comment by qdrop17** [comment]
Hi @morphis 

I would highly appreciate it, if Anbox would use the native window titlebars uf Ubuntu / Pop OS (just like in the demo video: https://www.youtube.com/embed/MbmiHnasGWg).

How can I build Anbox so this is enabled?

This piece of software has a big potential as it bridges two powerful ecosystems together :-).

Best

**Comment by thdaemon** [comment]
@alxlg 
@qdrop17 

I created a fork to reuse server-side decorations.

I don’t have any intention of creating a split community. In fact, because this requires changes to the Android framework layer (I actually just reverted the commit for adding title bar), but I am not familiar with Android framework development, otherwise I will help create a patch that you can configure the ssd/csd at runtime and submit a pull request. For now, just provide a fork version that always performs ssd always.

Anbox uses client-side decoration really badly. Some games don't have a title bar and click misplaced. And because of the lack of some things like `_GTK_FRAME_EXTENTS` in GTK+, the zoom area must be within the real window range. This makes buttons that occupy the border of the window difficult to click (Although a patch has made border smaller).

You can build my fork to use ssd. https://github.com/thdaemon/anbox

You must use this fork with a customed Android image. I build one and uploaded to here https://github.com/thdaemon/anbox/releases/tag/ssd-mod-v1
(If you want to build yourself, you can get source here: https://github.com/thdaemon/platform_manifests and here https://github.com/thdaemon/platform_frameworks_base/)

When the anbox developers actually implement configurable csd/ssd, I will delete the fork.

![1](https://user-images.githubusercontent.com/26319540/78355853-0af2d800-75e1-11ea-8f56-6a0a80b5fc89.png)

**Comment by morphis** [comment]
@thdaemon It would be really nice if we can make this configurable for the user. Instead of doing https://github.com/thdaemon/platform_frameworks_base/commit/0a150c78e7f5b73fdd653e921e6e9d0528b30dfc we can check in the code for a specific system property and use that as the condition to enable or disable Android side decorations. The property can then be set from Anbox when a specific command line option is set for the session process. What do you think?

**Comment by thdaemon** [comment]
@morphis 

Thanks for taking the time to reply. I think this is great. I have learned how to add property to an android container in anbox (like https://github.com/anbox/anbox/blob/6d9ada9d10348589a03d8101e7cb9f50d6d0b5fb/src/anbox/cmds/session_manager.cpp#L260).
But before this project, I didn't even have any experience of modifying the android framework code. Through Google search, I think that `SystemProperties.getInt` can be used to achieve our goal. Then can I call it in `init()` method of DecorCaptionView.java? This will not cause performance problems, right? Or do we have to get property in another place. (I don’t even know when and where the android framework code is running)

**Comment by alxlg** [comment]
@morphis the protocol to negotiate SSD vs CSD on Linux should be Freedesktop's xdg-decoration

**Comment by thdaemon** [comment]
@alxlg 
I have different opinions on this. First of all, xdg-decoration seems to be just an experimental extension of Wayland. There is also X11 in the Linux world.
Last but not least, I quickly read the specification file of xdg-decoration (If I missed something, please let me know). I found that xdg-decoration seems to have nothing to do with our problem. xdg-decoration seems to be a protocol for GUI clients to request the compositor to add or delete a decoration for themselves. But our problem is that some people in the anbox user group want to use CSD, the others want to use SSD. So I hope there is an option to allow users to make decisions before starting. When the user decides to use anbox with SSD option actived on the Wayland system, the library used by anbox (such as SDL) should communicate with compositor to enable the SSD, and we don't need to deal with this (When creating window without SDL_WINDOW_BORDERLESS, SDL should use this to enables SSD, on Wayland)
