### ISSUE TITLE
ERROR: adb: failed to install aplication.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by AlexVovo** [anbox/anbox#1314]
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
[please paste printout of `anbox system-info` here]
```
</details>

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment]
If you want any help it doesn't work that you just copy&paste an error message and don't fill out any of the requested details.

However in this particular case you're trying to install an APK which only supports an architecture your host system doesn't match (e.g. ARM on x86). This isn't bug but simply not possible to support in Anbox as of today.

**Comment by iamafasha** [comment]
So I have linuxmint 64 bit ? How do I know the apps I can install?

**Comment by flutterbrony** [comment]
You can use an apk with native x86 libraries in it. apkmirror can list them for you if you want.

Alternatively, if you can't find an apk with x86 libraries, you can build another android image to use in anbox.
The one provided with anbox don't have the arm translator that come with any commercial x86 android because it is under proprietary licence, but you can add it yourself. You can also install the Google APPS yourself. It's not included for almost the same reason as the arm translator.

Here a guide if you want to test it : https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html
