### ISSUE TITLE
CTS support

### ISSUE THREAD

**Issue by RossComputerGuy** [anbox/anbox#1365]
I was reading through #1134 and was wondering about SafetyNet working. I saw [this comment](https://github.com/anbox/anbox/issues/1134#issuecomment-492591722) which said that CTS is needed. I went through the CTS stuff and found [the development page](https://source.android.com/compatibility/cts/development). I was wondering if we could get the CTS source code and somehow reverse engineer it or something.

**Comment by RossComputerGuy** [comment]
Please don't close

**Comment by brucbr** [comment]
Going to give my opinion. I'm not a contributor towards this project so I wouldn't actually know.

Reverse Engineering a piece of software accurately is hard. No ifs ands or buts about it. Sure it could be reverse engineered to a point where it "passes" it, but the point of safetynet is to be accurate (Despite the multitude of bypasses on rooted devices).

 Also, reverse engineering something takes time. When something has been reversed engineered well, its because there was a lot of people and a lot of time. Usually a few months later, along comes a security patch and then bam it no longer works.

As far as I know, Anbox aims to just get applications working on linux and CTS/Safetynet is just not a priority and not worth the effort. Chances are a few weeks after google finds out about it working, they'll start working on a counter measure.
