### ISSUE TITLE
AUR is unable to located linux-headers-generic anbox-modules-dkms

### ISSUE THREAD

**Issue by Joe23232** [anbox/anbox#1390]
I am using an ARch-based distro and typing in `yay -S linux-headers-generic anbox-modules-dkms` results in an output:

```
==> Error: Could not find all required packages:
    linux-headers-generic (Target)
    anbox-modules-dkms (Target)
```

Is there another way to retrieve this?

**Comment by 86423355844265459587182778** [comment]
First of all, you should consider asking the question in the AUR package page, because Anbox does not officially supports Arch Linux or its derivatives.

Which AUR package are you trying to build? Have you tried [anbox-git<sup>AUR</sup>](https://aur.archlinux.org/packages/anbox-git)?

You can also try the [\[archlinuxcn\] repository](https://github.com/archlinuxcn/repo) as it contains the anbox packages, but note that it is aimed at Arch Linux users, so it may not work in your case.

Anbox does not have any stable release yet so it is impossible to have a `anbox-modules-dkms` package. You will find [anbox-modules-dkms-git<sup>AUR</sup>](https://aur.archlinux.org/packages/anbox-modules-dkms-git/) instead.

On Arch Linux you should install `linux-headers`, but since you are using an Arch derivative (and you did not give the exact name of the distribution you are using), I am afraid that you are on your own. Please look for the corresponding package(s) yourself, or ask for help in the corresponding community forums for your distribution.

**Comment by Joe23232** [comment]
@86423355844265459587182778 

> First of all, you should consider asking the question in the AUR package page, because Anbox does not officially supports Arch Linux or its derivatives.

Sure next time I will keep that in mind.

> Which AUR package are you trying to build? Have you tried anbox-git?

Yes I have and it installed just fine. When trying to install these packages `linux-headers-generic anbox-modules-dkms` (as suggested on your website) it fails to install.

> You can also try the [archlinuxcn] repository as it contains the anbox packages, but note that it is aimed at Arch Linux users, so it may not work in your case.

I am an Arch Linux user so I could give that a try.

> Anbox does not have any stable release yet so it is impossible to have a anbox-modules-dkms package. You will find anbox-modules-dkms-git instead.

Ok I could give that a try instead.

> but since you are using an Arch derivative (and you did not give the exact name of the distribution you are using)

I am using EndeavourOS, they claim to be very close to Arch Linux.

**Comment by 86423355844265459587182778** [comment]
> When trying to install these packages `linux-headers-generic` `anbox-modules-dkms` (as suggested on your website) it fails to install.

Sorry, where do you see the references to those 2 packages? Links or screenshots please?

In case you missed: on official Arch Linux's stock kernel, you should install `linux-headers`.

By "linux-headers-generic", are you referring to the Ubuntu package? Why are you using Ubuntu's package name for Arch's pacman?

Please try `sudo pacman -Syu linux-headers`, then build and install the `anbox-modules-dkms-git` AUR package.

**Let me repeat one more time: on official Arch Linux and official AUR repository, there are currently no packages named `linux-headers-generic` or `anbox-modules-dkms`**!

**Comment by Joe23232** [comment]
@86423355844265459587182778 

> Sorry, where do you see the references to those 2 packages? Links or screenshots please?

Sure mate

![image](https://user-images.githubusercontent.com/34926497/77149985-eda11280-6ae6-11ea-942d-f902aafbeaae.png)

> In case you missed: on official Arch Linux's stock kernel, you should install linux-headers

I already have it installed for the lts kernel and the main kernel.

> By "linux-headers-generic", are you referring to the Ubuntu package? Why are you using Ubuntu's package name for Arch's pacman?

I didn't know this was only for Ubuntu.

> TL,DR: Please try sudo pacman -Syu linux-headers, then build and install the anbox-modules-dkms-git AUR package.

I believe I alreayd have hte headers so I just need to build `anbox-modules-dkms-git` this then.

> Let me repeat one more time: on official Arch Linux and official AUR repository, there are currently no packages named linux-headers-generic or anbox-modules-dkms!

Got that mate.

**Comment by 86423355844265459587182778** [comment]
> I believe I already have the headers so I just need to build `anbox-modules-dkms-git` this then.

Correct!

Two important tips for you:
1. **A package can have different names in Distribution A and Distribution B.**
2. **A guide written for Distribution A does not necessarily work on Distribution B.**

I realize that you are trying to follow the instructions but that webpage is for **Ubuntu users**. It's another story on Arch Linux or EndeavourOS, so [ArchWiki's article on Anbox](https://wiki.archlinux.org/index.php/Anbox) is a more suitable guide for you to follow.

Some examples:
* Ubuntu and Kubuntu are similar, so a Kubuntu user can refer to Ubuntu's guide most of the times.
* Debian and Ubuntu have some differences, but some parts are similar, so a Ubuntu user can use Debian's guide *as a starting point*. Some modifications may be needed.
* Fedora and Ubuntu are very different, so a Fedora's guide is not really useful (and can be completely useless) for a Ubuntu user.

Since you are using EndeavourOS, you can refer to Arch Linux's documentation (mainly ArchWiki).
