### ISSUE TITLE
The resize targets are very wide and frequently prevent interaction with apps.

### ISSUE THREAD

**Issue by TimMagee** [anbox/anbox#1430]
**Please describe your problem:**
When I attempt to click on a click target near the edge of an app, I expect to click the click target under my mouse cursor rather than activating the resize functionality. 

**What were you expecting?:**
I expect that what is under my mouse cursor will receive the click event.

**Additional info:**
If we added window borders, they could be the drag targets. Some windows also provide drag targets just around the window. Or we could simply provide much narrower drag target while still allowing them to invisibly cover part of the app.

**Comment by thdaemon** [comment]
May be duplicated with #1308 

This problem is essentially because the library SDL used by anbox does not support CSD well. Because of the lack of some things like `_GTK_FRAME_EXTENTS` in GTK+, the resize targets must be within the real window range.

You can add window border when you using pull request #1415. It provides a configurable server-side decoration. When using server-side decorations, the border is managed by the window manager, so resize targets will not occupy the real window area.
Another tip is, The resize targets have been reduced once (pull request #1352). If you are using the latest version in this repository, the change is already included. If you are not using the latest version of this repository, you can try whether the new version is acceptable or not.

**Comment by TimMagee** [comment]
I downloaded the latest 'edge' version and it is much better. However, it can 
still be improved for usability.

I would like to suggest the following two improvements:

 1. Make the clickable border visible. (I realize this could be unpopular)
 2. Switch the mouse cursor to the 'resizing arrow' as soon as the user hovers 
over the resizing target rather than wait for a click. Then the resizing 
behavior would be much less unexpected.
