### ISSUE TITLE
how can I use android_10.0.0_r6 to build anbox image?

### ISSUE THREAD

**Issue by GitSoftwareNow** [anbox/anbox#1493]

**Comment by LuceCompany** [comment]
Try like here :
`https://github.com/anbox/anbox/blob/master/docs/build-android.md`

But change in the default.xml, clonned from : 
`https://github.com/anbox/platform_manifests/blob/anbox/default.xml`

* Change on ` refs/tags/android-7.1.1_r13" -> refs/tags/android-10.0.0_r38" ` In
```sh
<remote  name="aosp"
           revision="refs/tags/android-7.1.1_r13"
```
And from ` <default revision="refs/tags/android-7.1.1_r13 ` on ` <default revision="refs/tags/android-10.0.0_r38" `
```sh
<default revision="refs/tags/android-7.1.1_r13"
```
I didn't do it, so I don't know if it will work.
Give me the answer do you have built the image. I'm curious because i will do this same in future.

**Comment by AkihiroSuda** [comment]
There was an effort to port Android 10 to Anbox, but seems got stalled now
https://github.com/anbox/anbox/issues/1297
