### ISSUE TITLE
Installing anbox-modules-dkms fails on Ubuntu 18.04 LTS and lowlatency kernel version 5.3.0-59-lowlatency (x86_64)

### ISSUE THREAD

**Issue by BeFrankly** [anbox/anbox#1513]
Hello,

I'm trying to get anbox working to use a bt app for my new bt enabled multimeter (circuit analyzer).
I get stuck at the first step of installation procedure that I found here: https://github.com/anbox/anbox/blob/master/docs/install.md

Here is the rest of the output of command **sudo apt install anbox-modules-dkms** and the attached build.log

anbox-modules-dkms (13) wird eingerichtet ...
Loading new anbox-1 DKMS files...
Building for 5.3.0-59-lowlatency
Building initial module for 5.3.0-59-lowlatency
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/anbox-modules-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.3.0-59-lowlatency (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.

[make.log](https://github.com/anbox/anbox/files/4823325/make.log)

My system is a **Ubuntu 18.04 LTS** (flavor Ubuntu Studio) with a **lowlatency kernel** (because of doing home recording) and **Secure Boot enabled**.

After removing anbox-modules-dkms and trying synaptic, synaptic installs the package but also displays the error in the detail view.
**lsmod** listed the binder_linux module but not ashmem_linux.
sudo **modprobe** ashmem_linux ended with **"operation not permitted"**.

So I get stuck here. 

Need help
Disabling Secure Boot is no option.

Regards

Frank

**Comment by stevennyman** [comment]
You may need to sign the modules in order to run them.
First, try enabling the modules, which should be possible using: sudo modprobe binder_linux sudo modprobe ashmem_linux or sudo insmod binder_linux sudo insmod ashmem_linux.
If you get an "operation not permitted" error, you need to sign the modules for secure boot. I fixed this by running a command along the lines of sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der '/usr/lib/modules/5.4.0-40-generic/kernel/drivers/staging/android/ashmem_linux.ko', replacing 5.4.0-40-generic with your current installed Linux kernel version from uname -a (or replacing the third file path with the location of the kernel module file).
