### ISSUE TITLE
Not an issue, but could you take a look at this 'fork' and tell me what you think?

### ISSUE THREAD

**Issue by DaedalusBLN** [anbox/anbox#1514]
This guy offers a patched android.img and some configuration and patched files saying that Anbox has security issues. I'm wondering why he didn't commit to Github though, so I am unsure whether I should use his files. Call me paranoid.

Maybe the points he raises and the fixes he provides could be helpful to you though?

https://fjordtek.com/git/Fincer/anbox-install

If you have a moment could you please just skim through the README on his page and write a quick comment?

**Comment by Xerusial** [comment]
This should be added.

**Comment by Fincer** [comment]
Hi @DaedalusBLN

Happy to see you found my Anbox "fork". I recompiled the Android image since Anbox project does not provide any Android image with both audio timing and server-side decoration patches included at the moment. In my testing, I also noticed annoying feature which pauses default Gallery application (`com.android.gallery3d`) video/audio playback if any other Android application takes focus. This feature is also disabled in my Android image so desktop usage is more convenient and you can, for instance, play music and use another Android application simultaneously without interruptions. Nothing else has been changed.

One of the most obvious and common security issue is running Anbox container manager in *privileged* mode. For many, the privileged configuration "works" but it means that Android system processes run as real root on a Linux computer. Therefore, I see running Anbox container in unprivileged mode is quite essential and I wanted to find a way to do it _without snap overhead_. For instance, current Arch Linux [AUR package anbox-git](https://aur.archlinux.org/cgit/aur.git/tree/anbox-container-manager.service?h=anbox-git) uses privileged mode and I just don't like it. Additionally, I did short Systemd security analysis to restrict permissions of Anbox container service ([anbox-container-manager.service](https://fjordtek.com/git/Fincer/anbox-install/src/branch/master/anbox_files/anbox-container-manager.service)).

Additionally, I don't understand the current solution to purposefully hide `container-manager` options ([container_manager.cpp, line 41 (option true)](https://github.com/anbox/anbox/blob/c898810050df67adccd64a84b2d763250a42e722/src/anbox/cmds/container_manager.cpp#L41)) in Anbox help menu so I disabled the feature it in my fork. In my opinion, all possible program options should be displayed by default as it makes configuration more transparent and easier to figure out for end-users.

> I'm wondering why he didn't commit to Github though, so I am unsure whether I should use his files. Call me paranoid.

For some repositories, I just prefer my personal Git server. Nothing malicious here, although I fully understand your security concerns. I have thought about mirroring to GitHub, though. You can still check patch files yourself, compile the Android image and compare checksums if in doubt. You just need a lot of storage capacity for AOSP, ~300 GiB at the moment.

> Maybe the points he raises and the fixes he provides could be helpful to you though?

I hope so. I am just too impatient to wait for pull requests to be merged to the upstream. For instance, many users have asked the mentioned audio timing and server-side decoration patches to be merged to the Anbox Android image but barely nothing has happened, even after months of waiting.

**Comment by leandromqrs** [comment]
Hello @Fincer I saw that you understand the subject very well and is inside the source code of Anbox, have you considered talking to @morphis to be part of the Anbox organization? It's clear that @morphis needs help handling commits and pull-requests and I think you could be that guy.

**Comment by Fincer** [comment]
Hi @leandromqrs

I understand parts of the project source code and gain more knowledge when I find out some features which need improvements or are missing. Like some of us do. For the most parts, I write out information and code patches for myself and I am happy to share them with the Anbox community.

> It's clear that @morphis needs help handling commits and pull-requests

@morphis has done great job with the current Anbox codebase. However, I agree the project urgently needs contributional help in some parts such as in feature implementations and handling of pull request and commits. In the end, Anbox has great potential for Linux desktop users but still has some drawbacks.

> have you considered talking to @morphis to be part of the Anbox organization?

I'd be happy to help the Anbox community and the Anbox project. However, I have not considered talking to @morphis, at least not yet, since I am currently busy with several other projects. I may consider it in the future. Thanks for the suggestion!
