### ISSUE TITLE
Installation instructions for 20.04 are unclear

### ISSUE THREAD

**Issue by galgalesh** [anbox/anbox#1581]
There seem to be two separate installation docs:

* [github](https://github.com/anbox/anbox/blob/master/docs/install.md)
* [docs.anbox.io](https://docs.anbox.io/userguide/install_kernel_modules.html)

The second one is linked to from the website.

docs.anbox.io says the ppa is not needed anymore for 20.04:

> Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore.

Though it's unclear which steps are still needed on 20.04, though. I tried `sudo modprobe ashmem_linux` and this seems to work on 20.04; I get `/dev/ashmem`. `sudo modprobe binder_linux` doesn't do anything, though.

On top of that, the [github](https://github.com/anbox/anbox/blob/master/docs/install.md) docs don't mention that 20.04 doesn't need the PPA. What docs should I follow? Is it possible to merge the two docs so they don't get out of sync anymore?

**Comment by GizmoChicken** [comment]
> it's unclear which steps are still needed on 20.04

Agreed!  The instruction for installing onto 20.04 are confusing and should be updated.  But support for Anbox on Ubuntu 20.04 is recent, and maybe not entirely finished.  So that's probably why the instructions haven't yet been updated.  But yes, we should update/clarify the instructions soon!

Here's a start:

On stock Ubuntu 20.04, Anbox can be installed simply using:
```
sudo snap install --beta anbox --devmode
```

Once installed, attempt to start Anbox.  If Anbox starts, you're good!

If Anbox fails to start, confirm whether `binder` and `ashmem` loaded using: 
```
lsmod | grep -e ashmem_linux -e binder_linux
```

If one or both failed to load, try loading them using:
```
sudo modprobe ashmem_linux

sudo modprobe binder_linux
```

Confirm again whether `binder` and `ashmem` loaded using: 
```
lsmod | grep -e ashmem_linux -e binder_linux
```

If `binder` and `ashmem` loaded, try again to start Anbox.  If Anbox still won’t start, file a bug report.

**NOTE**:   Those having **Secure Boot** enabled on 20.04 *must* to add another ([simple](https://github.com/anbox/anbox/issues/1570)) step *before* attempting to load `ashmem`, otherwise `ashmem` will fail to load.
