### ISSUE TITLE
Anbox main window doesnt respect the black borders on Phosh on Pinephone

### ISSUE THREAD

**Issue by paju1986** [anbox/anbox#1615]
Using anbox on the pinephone with Phosh, the main window draws under the bottom and top black borders of the Phosh interface.

**Comment by necessarily-equal** [comment]
That one depends on Anbox wayland support, or Phosh XWayland support. The former would be really nice anyway, as it would fix other issues. See https://github.com/anbox/anbox/issues/1270 for one blocker

**Comment by GizmoChicken** [comment]
@necessarily-equal   Based on your above comment (and on the comments found in #1270), if I understand correctly, Anbox currently depends on X11, and thus, _at present_, can only run on a system that supports X11 or XWayland.   That is, Anbox can't currently run on a system that _only_ supports Wayland.  Is that correct?

**Comment by necessarily-equal** [comment]
That is correct. If you try hard enough, you can get Anbox to almost 
start on wayland, but it will not start (and if it would, it would 
never display anything because anbox use X11 pbuffers, see 
https://github.com/anbox/anbox/issues/1270)

Le dim 4 oct. 2020 à 21:41, GizmoChicken <notifications@github.com> a 
écrit :

**Comment by dos1** [comment]
1) This isn't an Anbox issue and IMO should get closed (the real issue would be Wayland support).
2) Current version of phoc deals with XWayland windows pretty well, so this is resolved anyway :P
