### ISSUE TITLE
Anbox HTTPS????

### ISSUE THREAD

**Issue by Mistero5050** [anbox/anbox#166]
![immagine](https://cloud.githubusercontent.com/assets/6240983/25303492/4a33b838-2754-11e7-85e9-21d6fc154f62.png)
How is this possible? I've also had to confirm an SSL security exception...
HTTPS site? 
You know that Let's Encrypt give free SSL certificates away, do you?

**Comment by morphis** [comment]
Actually this issue belongs to https://github.com/anbox/anbox.github.com 

However, we can't offer HTTPS support yet as anbox.io is currently hosted by github pages which doesn't provide HTTPS support. I know that Let's Encrypt gives free SSL certificates and that is what we will use starting next week when we move the site to an external server.

You get an SSL security exception on https://anbox.io/ because the certificate is only valid for *.github.com pages.

**Comment by Mistero5050** [comment]
Ok, thanks for explaining it. :+1:
