### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by Ryhon0** [anbox/anbox#1748]
What is the status of this project? The last commit to this repository was 29 days ago. I've heard Anbox Cloud is being developed, is the work from that project going to carry over to this one? Right now there's only one alternative - xdroid, which violates the GPL but has support for OpenGL and lets you play games.

**Comment by Shatur95** [comment]
It looks like the project is not developing. The author [working on a proprietary Anbox cloud for Cannonical](https://mm.gravedo.de/blog/posts/2020-01-21-taking-the-anbox-journey-to-the-next-level/). The post indicates that some things will be backported, but I don't think the author will actively develop the same project after his work.

It would be nice to have a someone who at least can review and merge PR's.

**Comment by afalout** [comment]
I agree with @Shatur95 , this project now looks a bit like abandonware. It is still somewhat usable, and with someone to do PR merging and build a more current Android image, it could continue to be usable for a period of time - even without ongoing development. 

Having said that, in my experience, only --edge works on recent distros, and almost always require tweaking (EGL_PLATFORM=x11, latest LXC is mandatory, distro packages are almost all broken and only serve to discourage new users ...)

I understand why Simon does not have time for the project, hopefully only for now, I thank him very much for his contribution to Linux community, and I wish him all the best with his current commercial project.

To start with, it would be very much appreciated if @morphis could update the community on his intentions and possibly help with transition or establishing some project maintenance delegations.

**Comment by Shatur95** [comment]
@morphis, we need you thoughts about it.

**Comment by tjssoldier** [comment]
Will be nice to know if there is any plans to implement new features and improve compatibility with android app and games

**Comment by afalout** [comment]
Does not seem that lead dev(s) have time for this project, not even handover.
What are the options for the comunity? 
Without at least the ability to merge PR's .....  dare I say it...?
:(

**Comment by clebercasali** [comment]
> Having said that, in my experience, only --edge works on recent distros, and almost always require tweaking (EGL_PLATFORM=x11, latest LXC is mandatory, distro packages are almost all broken and only serve to discourage new users ...)
Hello @afalout 
Could you please write a howto?
I've been struggling to get anbox working with newer liquorix kernels.
I could only get it to work with *ubuntu 20.04 / kernel 5.4.

**Comment by afalout** [comment]
@clebercasali - there is little point in writing HOWTO for a project that is without a maintainer and there is not way to fix or improve anything as there is nobody around with commit rights. :(
And there seems to be only 5 people interest in this thread, so there is not much point in forking either....
Wound be happy to be corrected.

**Comment by Dashon1** [comment]
I check in on this thread. I just didn't see much point in saying anything. I mean even if a bunch of people load this thread showing interest in the "Status of the project?" That doesn't really change anything. I hope that the project can be forked in the future if it is truly abandoned.

**Comment by afalout** [comment]
@d-air1 - it seems quite a strange situation in this case for forking.
@morphis  merged stuff just 9 days ago (https://github.com/anbox/anbox/pull/1765) so he is here, but clearly focusing on his commercial priorities. Nothing wrong with that.
However - Simon (@morpis) is the ONLY person registered and authorized to merge code, (actually the ONLY person associated officially with the project in any way officially as far as Github is concerned - https://github.com/orgs/anbox/people)
Which makes Anbox basically a private project with code licensed as OpenSource. And not an OpenSource project.
Which is the apparent reason why we have this tread, as there are a lot of people here on the Anbox Github pages, wanting to help or needing help, thinking this is an opensource PROJECT.
But it is not. Or so it seems to me.
So the best thing I can think of at the moment is to keep asking @morphis to please drop us a line on your position on this, and hopefully delegate some admin rights to at least 2 people so we can contribute and help others outside of your current focus. Please. Thank you :)

**Comment by hydrasho** [comment]
@morphis ?

**Comment by Fuseteam** [comment]
the last commit was 12 days ago, 29 days is not a long time when there is only one main developer, who works on the project in his spare time. please don't bother the developer like this, it doesn't help him spend more time on the project than is able to.

**Comment by afalout** [comment]
@Fuseteam  - I think you missed the point. This is about wanting to participate and help. How long ago code was committed, is not the issue here. 

However, since only one person has the sole admin rights to this project, we are wondering if any participation or help is actually desired by @morphis 

And the fact that he is not responding for 2 months on this ticket, after repeated mentions by different people, for many is just another indication that this is Simon's private project. Not intended to be an OpenSource project, for any aspects other then the license, and code being freely accessible.

Would love to be proven wrong.

But until then, I'll consider this matter closed. Over & out.

All the best to you all,
Andrej

**Comment by Fuseteam** [comment]
@afalout simon barely has enough time to respond on the telegram group and work on the project, pull request are also merged when appropiate. 

If you want to participate and help submit pull requests just like the other contributors, that's way more productive than pestering the maintainer with "hey, are you alive? Hey, say something! Hey, hey, hey"

Notice that none of the participants in this issue have the "contributor" tag and ask yourself: what obligation does he have from responding? Would any of the participants in this issue know when its appropiate to merge a pull request?

**Comment by Shatur** [comment]
> @afalout Simon barely has enough time to respond on the telegram group and work on the project, pull requests are also merged when appropriate. Heck, the last few commits over the past few months are all merged pull requests!

When I wrote my first message here, the PRs weren't merging.

> Notice that none of the participants in this issue have the "contributor" tag and ask yourself: what obligation does he have to respond? Would any of the participants in this issue know when it's appropriate to merge a pull request? Have any of the participants tried to submit a pull request? Why are the other contributors quiet on this 'issue'?

Because nobody wants to contribute to a project in which the author does not reply to any issue. How we can discuss a feature before the implementation? Or should I take the time to develop some feature / fix a bug that the author will reject on review stage?
But don't get me wrong, I am not blaming the author of the project. I can understand him, because he is working on a proprietary version of Anbox for Cannonical, I don’t think that after work he will want to work on a similar open source project. But I can understand why other users are concerned about the status of the project.

But UBports already started to working on a fork: https://github.com/Anbox-halium
I think it's for a reason.

**Comment by Fuseteam** [comment]
> > @afalout Simon barely has enough time to respond on the telegram group and work on the project, pull requests are also merged when appropriate. Heck, the last few commits over the past few months are all merged pull requests!
> 
> When I wrote my first message here, the PRs weren't merging.
your first message was written on february 17, according to the [history](https://github.com/anbox/anbox/commits/master) they was a commit on february 14 just 3 days prior; additionally a pr was merged on january 6 barely over a month prior so no, PRs __were__ merged and you simply didn't check 

> > Notice that none of the participants in this issue have the "contributor" tag and ask yourself: what obligation does he have to respond? Would any of the participants in this issue know when it's appropriate to merge a pull request? Have any of the participants tried to submit a pull request? Why are the other contributors quiet on this 'issue'?
> 
> Because nobody wants to contribute to a project in which the author does not reply to any issue. How we can discuss a feature before the implementation? Or should I take the time to develop some feature / fix a bug that the author will reject on review stage?

my point is people _are_ contributing, over 70 of them, and none of those contributors have pitched in this conversation. the people in this conversation have not submitted a single PR. if they had submitted a PR and it was merged for months are even years like #1034,  they could make a case but they haven't, that's what irks me the most. 
this type of issue doesn't help the author at all, if anything it hurts the project more then it helps. people who come here from google will wrongly get the impression that the project is "dead" despite 
a) pr being merged (we got a merge just last week!) and 
b)no one in this pr have submitted an pr that the was unanswered. 

what helps instead is 
a) submit a pr that improves the project whether or not the author merges it doesn't have to matter (see aegisub that project was dead for years, an active fork took over and now someone is revitalizing the original merging the improvements from the active fork). 
b) learn the code base and help solve issues. the author is free to do with his code what he wishes, and so is the community


> Don't get me wrong, I am not blaming the author of the project. I can understand him, because he is working on a proprietary version of Anbox for Cannonical, I don’t think that after work he will want to work on a similar open source project.
> But also I can understand why other users are concerned about the status of the project.

The author has already said that what can be used on anbox will we PR'ed to it long ago and he hasn't said otherwise. anbox cloud has a separate codebase and it does indeed look like it is taking the majority of his time, which is indeed understandable; he's paid to work on anbox cloud he's not paid to work on anbox

> UBports already started to working on a fork: https://github.com/Anbox-halium
> I think it's for a reason.

Anbox-Halium (now known as WayDroid) is not a fork of anbox, it is a different approach to using android in a lxc containers, originally it would make use of halium containers to get access to android phone hardware. something that doesn't apply to anbox. it shares almost no code with anbox either. it is also not a ubports project as boldly stated on the crowdfunding campaign it is a community effort from 1 passionate developer and 1 passionate user that develope for and use ubuntu touch. Ubuntu Touch also has very different needs then what anbox offers for the desktop. finally WayDroid does not support X at all it only supports wayland and mir (which is a wayland compositor)

**Comment by Shatur** [comment]
> your first message was written on february 17, according to the history they was a commit on february 14 just 3 days prior; additionally a pr was merged on january 6 barely over a month prior so no, PRs were merged and you simply didn't check

I just wrote a post a little after the last PR was merged. Before that, I've seen some good PRs that haven't been reviewed (but I must admit they were merged later after a ~month).

> my point is people are contributing

But such people are few (I mean recent contributors). If the author has lost interest in the project (which is quite understandable!) and he does not have enough time to support the project, it is worth looking for a co-maintainers. If the project is actively merging PR and issues are considered, people will contribute to such a project more often.
I just recently had a situation when I sent a PR (not here!), which did not merged, because the author has a different vision of the project. And that was my fault as I didn't discuss the idea with the author.

> Anbox-Halium (now known as WayDroid) is not a fork of anbox, it is a different approach to using android in a lxc containers, originally it would make use of halium containers to get access to android phone hardware. something that doesn't apply to anbox. it shares almost no code with anbox either

Hm... This is weird. On the developer's funding page he mention working on improving Anbox itself: https://www.whydonate.nl/fundraising/anbox
He then changed his plans and decided to go with a different implementation?

> it is also not a ubports project

Oh, yes, you completely right here. It's **for** UBports, not **by**. I was wrong.

**Comment by Fuseteam** [comment]
> 
> > my point is people are contributing
> 
> And it's cool! But it usually minor submissions (I mean recent contributions). I'm worried that no one would dare to send a massive change. If the author has lost interest in the project (which is quite understandable!) and he does not have enough time to support the project,

like i said it doesn't have to matter if someone sends a massive PR and it remains unanswered, if someone understand the code well enough to send a massive PR and it massively improves anbox then people can just use their "fork". it is open source software anyone can take the code and redistribute. granted the maintainer __is__ actively merging so he hasn't lost interest in the project and as such anything that massively improves will surely eventually be reviewed and merged.

>  it is worth looking for a co-maintainers. If the project is actively merging PR and issues are considered, people will contribute to such a project more often.

how do look for co-maintainer? surely the minimum requirement would be that they understand the codebase well enough. how do you know if someone understands the codebase well enough? PRs.......get where i'm going?

> I just recently had a situation when I sent a PR (not here!), which did not merged, because the author has a different vision of the project. And that was my fault as I didn't discuss the idea with the author.
> 

which is fine, it is fairly simple to contact the author outside of github. can't say much about how quickly he'll responds tho, i haven't attempted to do that as i'm not familiar enough with the code to do that.

> > Anbox-Halium (now known as WayDroid) is not a fork of anbox, it is a different approach to using android in a lxc containers, originally it would make use of halium containers to get access to android phone hardware. something that doesn't apply to anbox. it shares almost no code with anbox either
> 
> Hm... This is weird. On the developer's funding page he mention working on improving Anbox itself: https://www.whydonate.nl/fundraising/anbox
> He then changed his plans and decided to go with a different implementation?
>
he mentioned improving anbox **on Ubuntu Touch** which isn't exactly the same thing github.com/ubports/anbox has some changes that simply don't make sense on the desktop. the effort of improving that resulted in WayDroid. the dev of that project has told me they'll send a PR this way once things are stable

**Comment by Shatur** [comment]
> like i said it doesn't have to matter if someone sends a massive PR and it remains unanswered, if someone understand the code well enough to send a massive PR and it massively improves anbox then people can just use their "fork".

It matters. It is very frustrating when you are wasting time and your PR has not been reviewed.

> granted the maintainer is actively merging so he hasn't lost interest in the project and as such anything that massively improves will surely eventually be reviewed and merged.

I'm not agree here, it's not what called __actively merging__ but it's up to you.

> how do look for co-maintainer? surely the minimum requirement would be that they understand the codebase well enough. how do you know if someone understands the codebase well enough? PRs.......get where i'm going?

Usually, people open a pinned issue for this. This is how it usually done. But he just doesn't answer any issue.

> which is fine, it is fairly simple to contact the author outside of github. can't say much about how quickly he'll responds tho, i haven't attempted to do that as i'm not familiar enough with the code to do that. also #1799; it's not that he doesn't respond at all

When, in order to discuss something with the author, I need to find his contacts or send a ready-made implementation to get an answer, then this increases the entry threshold for contributors.

> the dev of that project has told me they'll send a PR this way once things are stable

So it's a fork?

**Comment by Shatur** [comment]
> well they can and as the current maintainer is still merging PRs, their PR will eventually be reviewed and merged. massives changes are also almost never done by "drive by" contributors (people who just want to make a change and disappears off the surface if the internet) so that is usually not an issue. if you're making massive changes, you benefit from those changes and others benefits from those changes, if by any change it gets rejected, then people that benefit from your changes will use your version, including yourself. additionally you will that know best how your code works. so at that point you would also be the one making improvements to your code and maintaining your code, cause they are that massive. those types of changes don't get merged in a day or two either as the original author also needs to gain an understanding of what you did and why you did it that way.

It looks like we have different points of view. I personally would not contribute to a project where the author does not respond to issues or merges small changes in months.

> don't know where you seen that happen

https://github.com/godotengine/godot-vscode-plugin/issues/244
https://github.com/asvetliakov/vscode-neovim/issues/319
https://github.com/Skycoder42/QHotkey/issues/50

>  ironically the OP hasn't said a word

Sure, as for all other issues.

> if you want to see an inactive project there are plenty of those on github as well

Nobody said that the project was inactive. 
For example: https://github.com/anbox/anbox/pull/1827#pullrequestreview-692680886. While I think it's wrong to bother the developer by writing spam, it looks like he just accidentally forgot to merge this PR. This is why I think that the project needs help with maintaining.
If the author answered here and said "No, I don't need a co-maintainer, will merge all this stuff by myself" - I would understand. But I suppose he didn't read this issue.

> his contact can be easily seen from a git show git commits include both a name and a email fwiw
>  also noticed that he did respond on WIP pr that i linked, didn't even do much yet and he tried to steer me in the right direction

Dude, I know how to use git. I meant that writing PM by email to discuss something or responding only to RPs cuts off potential contributors. But it's only my opinion, nothing else.

I hope I am wrong. I just explained why other people might think so.

**Comment by Fuseteam** [comment]
> It looks like we have different points of view. I personally would not contribute to a project where the author does not respond to issues or merges small changes in months.

sure does look like it, if i wanted to become a co maintainer of a project i notice need a hand; i would try to learn the codebase and try to make a meaningful contribution and if i managed to feel comfortable enough to maintain my own fork and/or gained/earned a reasonable amount from the maintainer would say request co-maintainership; but hey that's just me

> > don't know where you seen that happen
> 
> [godotengine/godot-vscode-plugin#244](https://github.com/godotengine/godot-vscode-plugin/issues/244)
> [asvetliakov/vscode-neovim#319](https://github.com/asvetliakov/vscode-neovim/issues/319)
> [Skycoder42/QHotkey#50](https://github.com/Skycoder42/QHotkey/issues/50)

thanks for the concrete examples
 
> > ironically the OP hasn't said a word
> 
> Sure, as for all other issues.

no i mean the person who opened this issue hasn't said a word since they opened it
 
> > if you want to see an inactive project there are plenty of those on github as well
> 
> Nobody said that the project was inactive.

that's what this issue is about isn't it? the opening comment literally opens with 
> What is the status of this project? The last commit to this repository was 29 days ago.

> For example: [#1827 (review)](https://github.com/anbox/anbox/pull/1827#pullrequestreview-692680886). While I think it's wrong to bother the developer by writing spam, it looks like he just accidentally forgot to merge this PR. This is why I think that the project needs help with maintaining.

yes he needs help but really noone that responded to this issue so far would even qualify for that role. none of the participants in this issue, including myself, have ever submitted a meaningful pull request. in that respect this issue is just......spam. it doesn't help the maintainer and no one in the thread would be able to help the maintainer either.

> If the author answered here and said "No, I don't need a co-maintainer, will merge all this stuff by myself" - I would understand. But I suppose he didn't read this issue.

i don't think he has enough time to respond to every little issue really, the community handles that for where possible so far

> Dude, I know how to use git. I meant that writing PM by email to discuss something or responding only to RPs cuts off potential contributors. But it's only my opinion, nothing else.
> I hope I am wrong. I just explained why other people might think so.

i mean if someone is motivated enough they can and will find a way to contact the maintainer but really most people don't have either the required skillset or the time time to co-maintain this project in a meaningfull way. you don't want to know how long (read years) the UBports foundation was trying to hire, yes hire a maintainer for anbox to advance it on ubuntu touch and also upstream the improvements. It wasn't untill a few community members started a crowdfunding campaign **and** reach out to a specific community member they found that waydroid came to be.

i'm sure you are aware but i'll reiterate for completeness the maintainer also has to trust the co-maintainer to not merge things that are malicious and such as well, unless of course he can find the time to review every single time to build that trust, making random people co-maintainers just isn't an option either. while a co-maintainer will ease the burden both appointing a co-maintainer and maintaining will cost time and resources

**Comment by Fuseteam** [comment]
> Sure, this is the most important requirement.

mhm that's why i think people who are up for it should just contribute and earn the trust of the maintainer ;)

> > that's what this issue is about isn't it? the opening comment literally opens with
> 
> It's more of a question. The project is definitely not dead. But I think that the project lacks resources.
> 
> > yes he needs help but really noone that responded to this issue so far would even qualify for that role.
> > in that respect this issue is just......spam.
> 
> Sad but true.
> However, I can understand why people ask too. But I agree that it doesn't help at all.

looks like we agree here :)

> > you don't want to know how long (read years) the UBports foundation was trying to hire, yes hire a maintainer for anbox to advance it on ubuntu touch
> 
> Wow, I didn't know. But I was very happy when I found out about Waydroid, because I use Anbox mostly on my phone. Hope that the desktop experience will be improved too.

you and me both mate, i think the biggest issues are really time, skills and trust.

**Comment by anjannath** [comment]
Looking at https://github.com/waydroid/waydroid now, i think we can move to using waydroid, still need to thoroughly test this tough, @Ryhon0 is the xdroid project still mainted (please provide a link to the project)

**Comment by clebercasali** [comment]
Waydroid depends on Wayland, which is not really feasible for Nvidia users.

**Comment by Ryhon0** [comment]
> Looking at https://github.com/waydroid/waydroid now, i think we can move to using waydroid, still need to thoroughly test this tough, @Ryhon0 is the xdroid project still mainted (please provide a link to the project)

It seems like xdroid is still getting updated, here's the link to it https://www.linzhuotech.com/index.php/home/index/xdroid.html

**Comment by Fuseteam** [comment]
what's xdroid? and how that related to anbox?

**Comment by anjannath** [comment]
> > Looking at https://github.com/waydroid/waydroid now, i think we can move to using waydroid, still need to thoroughly test this tough, @Ryhon0 is the xdroid project still mainted (please provide a link to the project)
> 
> It seems like xdroid is still getting updated, here's the link to it https://www.linzhuotech.com/index.php/home/index/xdroid.html

interesting, but am not able to find their source code repositories, is it open source?

**Comment by Ryhon0** [comment]
It's not. There's already a few issues talking about it violating the license
