### ISSUE TITLE
Combability for Windows 7 and above

### ISSUE THREAD

**Issue by HydrotronExe** [anbox/anbox#1825]
Would it be awesome if we modify AnBox source code and compile the same for windows?
Would the team care to respond since most of the world's market still uses windows 7?
Please help us

**Comment by hydrasho** [comment]
it's impossible because anbox need a kernel linux because we can add some module android

**Comment by 1Maxnet1** [comment]
> Would it be awesome if we modify AnBox source code and compile the same for windows?
> Would the team care to respond since most of the world's market still uses windows 7?
> Please help us

Additionally Windows 7 has reached End Of Life. So I don't see any reason why someone would want to support and EoL operating system.

**Comment by HydrotronExe** [comment]
New windows 11 is out there. Can you copy some of your code and make anbox on windows like the WINE project or something like that. It will offer new opportunities. Hope anybody wants to collaborate for that, please contact me at mvkb2006@outlook.com

**Comment by 1Maxnet1** [comment]
> New windows 11 is out there. Can you copy some of your code and make anbox on windows like the WINE project or something like that. It will offer new opportunities. Hope anybody wants to collaborate for that, please contact me at [mvkb2006@outlook.com](mailto:mvkb2006@outlook.com)
See the answer by @hydrasho Windows 7 or 11, it won't work.

**Comment by Gurbuzguven** [comment]
You can run Bluestacks(proprietary VM based solution), or running androidx86 under virtualbox(FOSS VM based solution) is more feasible for Windows users. There are two reasons:

1-Android is an open source Linux kernel based OS, and Windows uses proprietary closed source NT kernel, so you still need to run Linux kernel or compability layer for Linux kernel to run Android. Because of Windows kernel is closed source and these two kernels not alike it is near impossible to write a compability layer. Even Microsoft themselves uses a VM for Linux(a.k.a. WSL)

2- As your best is running linux inside a vm why not directly run android inside a vm?

**Comment by Fuseteam** [comment]
both android and "Desktop linux" are based around the linux kernel, it simply cannot work on windows without some form of virtualization. windows ships a linux kernel starting from windows 10. windows 7 simply cannot support anbox in any way shape or form
