### ISSUE TITLE
Can i root anbox device?

### ISSUE THREAD

**Issue by arzenstar** [anbox/anbox#209]
can i root mya anbox device / grant root access on anbox device ?

<b>anbox system-info</b>
version: 0.1.0
os:
  name: Linux Mint
  version: 18.1 (Serena)
  snap-based: false
kernel:
  version: Linux version 4.4.0-75-generic (buildd@lgw01-21) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
      - EGL_WL_bind_wayland_display
      - EGL_WL_wayland_eglstream
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 1.1 NVIDIA 375.39
    extensions:
      - GL_EXT_debug_label
      - GL_EXT_map_buffer_range
      - GL_EXT_robustness
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_format_BGRA8888
      - GL_KHR_debug
      - GL_NV_texture_compression_s3tc
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_compressed_paletted_texture
      - GL_OES_draw_texture
      - GL_OES_EGL_image
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_extended_matrix_palette
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_matrix_get
      - GL_OES_matrix_palette
      - GL_OES_packed_depth_stencil
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_OES_rgb8_rgba8
      - GL_OES_read_format
      - GL_OES_stencil8
      - GL_OES_texture_cube_map
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float

<b>Problem:</b>
grant root access

<b>Expecting:</b>
Rooted device

<b>Additional info:</b>
work well using "make install", but i run /anbox/scripts/anbox-bridge.sh manualy

**Comment by morphis** [comment]
> can i root mya anbox device / grant root access on anbox device ?

You can use `adb shell` and `su` to become root inside the container quite easily.

**Comment by DovaMerith** [comment]
Thats not what he was asking

He was asking how to use apps like SuperSU for ROOTED APPS, you know, like a ROOTED ANDROID PHONE?

**Comment by Zach-15803** [comment]
I think it would be something as easy as getting the su binary moved into the proper path, and installing the app, but i don't know as the squashfs stuff is sorta confusing.

**Comment by lukezene** [comment]
I can't become root on command line inside the Android container with "su" command, when i try the following error occurs:
`/system/bin/sh: su: can't execute: Permission denied`
I'm using ArchLinux.

**Comment by DovaMerith** [comment]
@lukezene You have to somehow ROOT your anbox installation to use the SU binary, its like this because Android natively doesnt let people use the SU binary with where its stored, only specific user level can use it. Which rooting it would let you use it because it creates a program that executes itself, and then logs in to the root level, and executes the SU binary

Atleast thats how i think its works, 

If you manage to reliably root anbox, TELL EVERYONE

**Comment by morphis** [comment]
You can easily get root on the command line via the anbox.shell command. If you want to place a su binary in the rootfs use https://docs.anbox.io/userguide/advanced/rootfs_overlay.htmlIf you want to tell everybody about how you did it extending the documentation at https://github.com/anbox/docs is the best way.Am 07.08.2018 18:08 schrieb DovaMerith <notifications@github.com>:@lukezene You have to somehow ROOT your anbox installation to use the SU binary, its like this because Android natively doesnt let people use the SU binary with where its stored, only specific user level can use it. Which rooting it would let you use it because it creates a program that executes itself, and then logs in to the root level, and executes the SU binary
Atleast thats how i think its works,
If you manage to reliably root anbox, TELL EVERYONE

**Comment by baptx** [comment]
@morphis the `su` command worked in Anbox until I tried to add a MITM certificate in android.img in the snap package with the squashfs commands from https://github.com/geeks-r-us/anbox-playstore-installer/commit/3e8082f4861e882e3344c7c6f5c7289a1aa7c336 (I cannot use rootfs-overlay because of this bug with frida-server: https://github.com/anbox/anbox/issues/1368).
Now when using `su`, I get the error `/system/bin/sh: su: can't execute: Permission denied` even when restoring the original snap package /var/lib/snapd/snaps/anbox_187.snap, do you know why?
Hopefully the workaround with `sudo anbox.shell` works. But isn't it possible to avoid running it as root? I guess it would be more secure (the su command worked without being root I think since Anbox uses an unprivileged LXC container).
