### ISSUE TITLE
Anbox kills Chromium

### ISSUE THREAD

**Issue by filicado** [anbox/anbox#351]
The Anbox Snap package (so much for isolation) has destroyed my chromium that now takes a minute to open under 16.04

Other people have seen the same thing:

https://askubuntu.com/questions/932281/anbox-made-chromium-open-slowly-in-ubuntu-16-04

**Comment by filicado** [comment]
So I just noticed some other apps are also affected. 
So do not install Anbox snap! It seriously will harm your system.

**Comment by morphis** [comment]
Did you actually prove it is Anbox and not chrome who causes this? What happens when you remove Anbox?

**Comment by filicado** [comment]
After complete removal of the anbox and anbox installer snap package chrome is still broken
As I gather it has something to do with the gnome-keyring-daemon which breaks when Anbox is installed (or launched).

**Comment by morphis** [comment]
Can you reproduce this behavior on a clean system? I've seen bug reports recently which are unrelated to Anbox but describe a similar behavior with recent Chrome versions.

**Comment by filicado** [comment]
I'm afraid I don't have any clean systems around :)

**Comment by morphis** [comment]
@filicado No VirtualBox or such alike?

**Comment by gmplp** [comment]
I have the exact same problem. Can't reproduce it on a clean system, but chrome and vivaldi (which is based on chromium) were working perfectly, I installed anbox with Vivaldi open, anbox asked me to reboot the system and chrome and vivaldi were broken (they take minutes to open). Nothing changed uninstalling Anbox. Difficult to tell that it is not Anbox that has broken it...

**Comment by grandtoubab** [comment]
No issue with chromium Version 59.0.3071.104 (Build de développement) built on Debian 9.0, running on Debian buster/sid (64 bits)
I installed Anbox and remove it using

sudo snap remove anbox

Check with 

debian:~$ snap info anbox
name:      anbox
summary:   "Android in a Box"
publisher: morphis
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
channels:                
  beta:   1-dev     (15) 357MB devmode
  edge:   3-ca59f27 (42) 358MB devmode

The little slow in the first opening is because HttpsEverywhre extension but this is my choice

**Comment by filicado** [comment]
Manually launching gnome-keyring-daemon in the terminal causes Chromium to launch immediately afterwards. So I guess the title should be "Anbox kills gnome-keyring-daemon" instead.

**Comment by gmplp** [comment]
So, look at this Ubuntu's bug:
https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1689825

It seems that the problems comes from package "dbus-user-session", that in our case came in through anbox, I guess. For me, uninstalling dbus-user-session solved the problem.

**Comment by filicado** [comment]
Why is this not removed when anbox is purged?

**Comment by morphis** [comment]
@gmplp Good spot!

@filicado It could be that something else on your system depends on it still.

All in all with the changes we did recently to the `anbox launch` command (spawning the session manager) if it isn't up and running we can drop `dbus-user-session` again.
