### ISSUE TITLE
anbox session-manager [EE 2017-08-14 22:09:54] [daemon.cpp:58@Run] bind: Address already in use

### ISSUE THREAD

**Issue by metaphizix** [anbox/anbox#405]
Hi
I cannot run anbox anymore this what I get when I try and run anbox.
![screenshot from 2017-08-15 01-02-52](https://user-images.githubusercontent.com/20734249/29295772-7e29d81e-8156-11e7-9681-2f9f54021394.png)

so is it seem like VMware and anbox are using the same local address or port so is it possible for me to change the address being used by anbox

**Comment by morphis** [comment]
I am not I understand why you think VMware and Anbox are using the same local address.

The reason why you're getting the error message "Address already in use" is because you have started the Anbox session manager already. The screenshot shows that both the container-manager and the session-manager are already running. If you want to run an Android application simply start it via the launch command like 

`$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity`

where you provide the Android package and component to start (in this case the Anbox AppViewer)
