### ISSUE TITLE
Add support for Linux Mint, please

### ISSUE THREAD

**Issue by fcex** [anbox/anbox#593]
I've been starting using Linux, and I really need an efficient tool for Android emulation. The only problem is that, as you would know, Linux Mint is not on the supported distros.

**Comment by RealPipeline** [comment]
This project seems to be moving along reallllly slowly, you're better off looking somewhere else

**Comment by DarthSpock** [comment]
It *should* still work for Linux Mint as it's based on Debian (Actually it's really based on Ubuntu, which in turn is based on Debian).

**Comment by ValkiryXDA** [comment]
i have a package for 17.10 ubuntu that works. unfortunately mint generally uses LTS distributions as a base. so untill the support 17.xx you cant really get it to work thanks to the bugs that plague 16.04

**Comment by DarthSpock** [comment]
I do believe that's what backports are for. If Linux mint doesn't have it in backports, you can "try" vim or nano /etc/update-manager/release- upgrades and change Prompt=normal. Save then do-release-upgrade (be sure to apt update, upgrade, and dist-upgrade before changing from LTS to normal in file.) Repeat the apt commands and then do-release-upgrade again and repeat until you get to 17.10. Be sure to lsb_release -a before trying to upgrade again as you can actually upgrade to alpha version of 18.04. You'll know you went too far if you see "bionic".

**Comment by Hoimar** [comment]
There's one installation issue with 18.04: The PPA that's needed for some Anbox modules does'nt have packages for 18.04 yet, so I had to manually cut out the PPA parts of the installer script, download the DEB packages by hand and install them. After that the installation went fine.
But Anbox still didn't run whatsoever, just like on 16.04 before.

> i have a package for 17.10 ubuntu that works. unfortunately  mint generally uses LTS distributions as a base. so untill the support  17.xx you cant really get it to work thanks to the bugs that plague  16.04
--

My last hope is trying it on a Ubuntu 17.10 now (not Xubuntu as before). 😆

**Comment by DarthSpock** [comment]
Actually I would try Kubuntu before Ubuntu first. By it's very nature, it's a bit more ahead than Ubuntu and does have a backports repository for all the 18.04 packages. Just be aware there are currently no 18.04 repositories for Kubuntu. All Kubuntu packages currently live in regular Ubuntu repositories on 18.04 (noticed when i tried an add apt-repository and got a nice error stating the Kubuntu ppas don't exist). If you do go the KDE route, KDE-Neon might be another option as well though I would stay on stable for 17.10. Haven't tried Anbox on that yet as there are a few issues when you simply add the ppa vice installing from boot ( a few packages that need updating have difficulty doing so due to dependencies that don't exist in the Neon repo, but this is on Xenial, can't upgrade without it jumping straight to 18.04, which is quite annoying and I don't want to install from boot when I'll most likely lose my files). KDE-Neon does seem pretty cool though from what I've seen of it.
