### ISSUE TITLE
fedora 27 not work install

### ISSUE THREAD

**Issue by amidevous** [anbox/anbox#687]
https://docs.snapcraft.io/core/install-fedora

#sudo dnf install snapd

#sudo ln -s /var/lib/snapd/snap /snap

#snap install --classic anbox-installer

so far, so good

but then

#anbox-installer
bash: anbox-installer : command not found

#ls /snap

anbox-installer  bin  core  README

#ls /snap/bin

anbox-installer

#/snap/bin/anbox-installer

 is not a clean path: "/run/lightdm/andy/xauthority"
Anbox (Android in a Box) - Installer

IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!

PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.

ERROR: You are running the installer on an unsupported distribution.
       At the moment we only support the following distributions:

Ubuntu, LinuxMint, neon, elementary

If your distribution is in the list but you still see this message, open
an issue here: https://github.com/anbox/anbox-installer

snap and precisely planned to allow the use of any linux program on all it is variant

but for that you had to include all compillation addiction in your snap package

**Comment by NobodyXu** [comment]
I, too, got the same situation when using snap, but I didn't go further into ```~/snap```.

Instead, I downloaded the script from the offical github repository readme, and it printed the same message to me.

I'm wondering why they add that message and prevent us from installing on a distribution that doesn't get offical support.

Isn't that better to allow us to install on such distribution easily with snap, so that we will actually test the software for them?

Why block that?
