### ISSUE TITLE
Difficult to install on Fedora system

### ISSUE THREAD

**Issue by lineber** [anbox/anbox#771]
After searching for each dependency and installing it, I still get the following error. Not file names are different on Fedora, and I cannot determine what properites-cpp is to. I suppose it is gcc related but even with installing those files it still persists.

Here's the error:

-- Checking for module 'properties-cpp'
--   Package 'properties-cpp', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:418 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:585 (_pkg_check_modules_internal)
  CMakeLists.txt:70 (pkg_check_modules)

**Comment by morphis** [comment]
@lineber We're not building well on anything else than Debian or Ubuntu yet. properties-cpp is not packaged for Fedora as far as I know (upstream is https://launchpad.net/properties-cpp). 

If you just want to run Anbox please use the snap you can install on Fedora as well. The only thing you need to do next to installing the snap (see https://docs.anbox.io/userguide/install.html) is to install the kernel dkms packages by following https://github.com/anbox/anbox-modules

**Comment by sergiomb2** [comment]
https://build.opensuse.org/package/show/home:gasinvein:anbox/properties-cpp

**Comment by sergiomb2** [comment]
dnf config-manager --add-repo=http://download.opensuse.org/repositories/home:/gasinvein:/anbox/Fedora_27/home:gasinvein:anbox.repo 

or get here the link for repo that fit with your system http://download.opensuse.org/repositories/home:/gasinvein:/anbox/ 

after 

    dnf install anbox android-tools 

after dkms run you may load modules with: 

     systemctl restart systemd-modules-load.service


after we need download android_amd64.img  from here  https://build.anbox.io/android-images/2018/06/12/ and copy to /var/lib/anbox/ as android.img 

now you may start services 
`systemctl start anbox-bridge anbox-container-manager adb`

now as normal user 

```
systemctl --user start anbox-session-manager
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```

also 
`adb shell `
or 
`adb install aptoide-8.6.4.1.apk`

now my goal is do an android.img with google play https://github.com/anbox/anbox/issues/118 and https://github.com/geeks-r-us/anbox-playstore-installer but we have to modify all script because we don't use snaps anymore hopefully 

Best regards,

**Comment by lineber** [comment]
@sergiomb2  Thanks, that totally worked after I changed the repo location to the Fedora28 version. It installed and launches.
Thanks again.

**Comment by sergiomb2** [comment]
> @sergiomb2 thanks it worked setting Selinux as permissive. Good job
> question: do you know how to set rootfs overlay options without snap?

On my fedora box I have SELinux *always* disabled .
 set rootfs overlay ? no.  What you mean ? 
I'd like have google services and drm permission to  use an tv app made by my ISP, in Portugal  , it works on androids [1] but use drm. 

[1] 
https://www.google.com/search?q=meo+go+android+app

**Comment by Fickri-s** [comment]
@sergiomb2 by this line,

> after **dkms run** you may load modules with:

do you mean doing these steps elaborated here? https://github.com/anbox/anbox-modules

**Comment by sergiomb2** [comment]
you will see that `dnf install` will run dkms , so dnf will perform [1] after see that text, you may run  systemctl restart systemd-modules-load.service which is the same of [2] 

[1]
$ sudo dkms install anbox-ashmem/1
$ sudo dkms install anbox-binder/1

[2]
$ sudo modprobe ashmem_linux
$ sudo modprobe binder_linux

**Comment by Fickri-s** [comment]
@sergiomb2 have you successfully installed playstore, using:

> now my goal is do an android.img with google play #118 and https://github.com/geeks-r-us/anbox-playstore-installer but we have to modify all script because we don't use snaps anymore hopefully
?

**Comment by sim590** [comment]
> have you successfully installed playstore

I'm trying to do the same right now by changing variables consistently with my debian package installation. The `rootfs` directory is under `/var/lib/anbox` so you can easily change the variable for that in the script. However, the system stays write-protected. It has to do with the following command I think:

```
snap set anbox rootfs-overlay.enable=true
```

That command is not usable anymore since installation is not done with `snap` anymore. So, I'm stuck there too and I would like it if someone had an idea to unstuck this thing. I guess it's just a matter of unsetting write protection on the `rootfs` directory?

**Comment by anjannath** [comment]
Hi, i have followed the steps mentioned in https://github.com/anbox/anbox/issues/771#issuecomment-401576229

But the service `anbox-session-manager` is not starting for me
```
$ journalctl --user anbox-session-manager
Nov 05 23:18:58 localhost.localdomain systemd[2553]: Started Anbox session manager.
Nov 05 23:18:58 localhost.localdomain anbox[2564]: Failed to connect to socket /run/anbox-container.socket: No such file or directory
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Main process exited, code=exited, status=1/FAILURE
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Failed with result 'exit-code'.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Service RestartSec=100ms expired, scheduling restart.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Scheduled restart job, restart counter is at 1.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: Stopped Anbox session manager.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Start request repeated too quickly.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: anbox-session-manager.service: Failed with result 'exit-code'.
Nov 05 23:18:58 localhost.localdomain systemd[2553]: Failed to start Anbox session manager.
```

What am i doing wrong?

**Comment by raffaem** [comment]
@morphis The [properties-cpp](https://github.com/lib-cpp/properties-cpp) project seems abandoned. Last update was 2018. This dependency should be dropped.

**Comment by sergiomb2** [comment]
> @sergiomb2 have you successfully installed playstore, using:
> 
> > now my goal is do an android.img with google play #118 and https://github.com/geeks-r-us/anbox-playstore-installer but we have to modify all script because we don't use snaps anymore hopefully
> 
> ?

no , I didn't tried

**Comment by sergiomb2** [comment]
https://salsa.debian.org/zhsj/anbox/-/blob/master/debian/README.Debian

**Comment by Fuseteam** [comment]
@raffaem ut will need  replacement to fulfill the role it currently plays
