### ISSUE TITLE
Problems compiling on ARM

### ISSUE THREAD

**Issue by HelloOO7** [anbox/anbox#838]
Build system: Raspberry Pi 3 on Debian Stretch, arm-unknown-gnueabihf

Compile flags: 
cmake .. -DCMAKE_CC_COMPILER=/usr/local/gcc-7.2.0/bin/gcc-7.2.0 -DCMAKE_CXX_COMPILER=/usr/local/gcc-7.2.0/bin/g++-7.2.0 && make

Build log: https://drive.google.com/file/d/1kBvOnhsB4SDfH7cKi7PjNcUz7czKawZB/view?usp=sharing

Building Anbox on RPi3 results in lots of errors, though most of them are redundant declarations in included files. Also, cpu_x86 has some issues due to some x86 exclusive code.

**Comment by morphis** [comment]
@HelloOO7 Building on ARM is currently not a focus of the core developers. That said, contributions (PRs) are always welcome to make it build on ARM.

**Comment by zhsj** [comment]
FWIW, it builds well on armhf and arm64, see build log on https://buildd.debian.org/status/package.php?p=anbox

**Comment by Askmewho** [comment]
I have the exact same error when attempting to compile the project

**Comment by baptx** [comment]
Did someone manage to run Anbox on Raspberry Pi? Does the Anbox Debian package work well? I would be interested to buy a Raspberry Pi to run Android apps that contain ARM native code.

**Comment by Askmewho** [comment]
I should try it again on rpi4. I did try it on rpi3 and it does run but crash

**Comment by nihsotas** [comment]
> 
> 
> @HelloOO7 Building on ARM is currently not a focus of the core developers. That said, contributions (PRs) are always welcome to make it build on ARM.

If you can not create multiple platform applications of opensource in opensource world of Linux, go program in Windows and stop to be an amateur.

**Comment by nihsotas** [comment]
If you can not create multiple platform applications in opensource world build in the Linux flavor, stop your amateurism and go to program in Windoz. Jesus.  You all start projects and if You start to test them they fail in stability, portability and can not compile in multi arch because You program or fix things as fast as they deliver a Mac Donald Burger.  That is not what the community expects of such projects. If you can not do that, quit and program in windoz, but do not spoil github with projects that do not work, do not compile or lack, in this case, also functionality (3d accel).
> 
> 
> @HelloOO7 Building on ARM is currently not a focus of the core developers. That said, contributions (PRs) are always welcome to make it build on ARM.
