### ISSUE TITLE
Question regarding anbox and security for host OS

### ISSUE THREAD

**Issue by WPFilmmaker** [anbox/anbox#880]
I couldn't find a similar ticket so decided to ask here.I haven't understood what "container" means in the case of Anbox, I think it doesn't work as a virtual machine. I was wondering, what are the safety-wise implications of running an app inside anbox for the host OS? 

On VirtualBox the OS is protected if a file infects the virtual os, on Wine I read that it can execute malicious code like if it was Windows, but what about Anbox? What happens if a malicious app is run inside Anbox? Can it affect the host OS as well? Does anyone have had issue with this?

**Comment by morphis** [comment]
@WPFilmmaker Anbox runs Android in an unprivileged container. You can easily find more information about this on the internet (see https://chromium.googlesource.com/chromiumos/platform2/+/master/arc/container-bundle/ for example) but effectively it makes everything inside the container run in an unprivileged UID namespace where the base UID starts at `100000`. So root inside the container isn't root on the host. That already renders a very powerful barrier in place to prevent the Android container from doing bad things to your host system. Also Anbox abstracts all hardware access so that the Android container never talks to any of your hardware components directly.

In the near future we will also add confinement support for the snap so that Anbox is allowed to do less on your host system (like running `apt-get`, overriding your kernel). That combined with the the secure container it provides for the Android system should make it quite secure (leaving any bugs in the software aside).

**Comment by baptx** [comment]
@morphis Is AppArmor used on top of the LXC container? I guess without AppArmor, an Android app could read or remove user files on the host OS even if it is running in an unprivileged container?
By the way, is each Android app running in it's own container or it is using a shared container with other apps? If it is using a shared container, it would mean that an Android app could spy on other Android apps? (e.g. config files)

**Comment by agentspawn** [comment]
> @WPFilmmaker Anbox runs Android in an unprivileged container. You can easily find more information about this on the internet (see https://chromium.googlesource.com/chromiumos/platform2/+/master/arc/container-bundle/ for example) but effectively it makes everything inside the container run in an unprivileged UID namespace where the base UID starts at `100000`. So root inside the container isn't root on the host. That already renders a very powerful barrier in place to prevent the Android container from doing bad things to your host system. Also Anbox abstracts all hardware access so that the Android container never talks to any of your hardware components directly.
> 
> In the near future we will also add confinement support for the snap so that Anbox is allowed to do less on your host system (like running `apt-get`, overriding your kernel). That combined with the the secure container it provides for the Android system should make it quite secure (leaving any bugs in the software aside).

Can someone please clarify "like running `apt-get`, overriding your kernel?" Are apps somehow able to run shell commands on the host?
