### ISSUE TITLE
docker and LXC

### ISSUE THREAD

**Issue by joeblew99** [anbox/anbox#97]
Its possible with docker and some custom OS Desktop code to run android app in a x11 window view. 
I am wondering if this is something you would be interested in.

here is some simple example :
https://blog.jessfraz.com/post/docker-containers-on-the-desktop/

I am guessing that this would need more work to support freeform multiwindow mode that Android 7 demands though, but its doable.

**Comment by morphis** [comment]
We're exactly doing this but using LXC as our container technology. The freeform multiwindow mode in Android 7 is what anbox uses to allow the multi-window functionality to work.

**Comment by joeblew99** [comment]
SO we can do it on Windows and OSX but i doubt your interested in this ?
https://blog.jessfraz.com/post/getting-towards-real-sandbox-containers/

at the bottom are links to the projects doing it.

I use this currently: https://github.com/jessfraz/binctr
Only because i am better at golang.

**Comment by morphis** [comment]
We use all available container technologies (namespaces, ..) already and the Android container is meant to be secure once we have everything in place. 

Something like "Can be run by an unprivileged user" what the referenced binctr does is not possible as the container needs things which can work this way due to restrictions on the kernel side.
