### ISSUE TITLE
Snapchat installs but doesn't run

### ISSUE THREAD

**Issue by frankliu197** [anbox/anbox#998]
I have downloaded snapchat from https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-9-11-0-0-release/snapchat-9-11-0-0-android-apk-download/
It installs successfully but when I try to run it the screen looks like the following.
![image](https://user-images.githubusercontent.com/23513458/50103816-82d39e00-01f6-11e9-88d4-1ed73e56729c.png)

This issue seems fairly similar to https://github.com/anbox/anbox/issues/976, which hasn't been solved. I thought I might highlight the issue by posting my problem and the diagnstic data as well.

5. Run the anbox logs collection utility and attach the tar file.
[anbox-system-diagnostics-2018-12-17.zip](https://github.com/anbox/anbox/files/2687117/anbox-system-diagnostics-2018-12-17.zip)
 

6. ** Please paste the result of `anbox system-info` below:**
version: 4
snap-revision: 158
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: elementary OS
  version: 5.0 Juno
  snap-based: true
kernel:
  version: Linux version 4.15.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: NVIDIA
    version: 1.4
    extensions:
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_output_base
      - EGL_EXT_stream_acquire_mode
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context_no_error
      - EGL_KHR_context_flush_control
      - EGL_KHR_create_context
      - EGL_KHR_display_reference
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_partial_update
      - EGL_KHR_swap_buffers_with_damage
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_stream
      - EGL_KHR_stream_consumer_gltexture
      - EGL_KHR_stream_cross_process_fd
      - EGL_KHR_stream_fifo
      - EGL_KHR_stream_producer_eglsurface
      - EGL_KHR_surfaceless_context
      - EGL_NV_nvrm_fence_sync
      - EGL_NV_post_sub_buffer
      - EGL_NV_stream_metadata
      - EGL_NV_stream_reset
      - EGL_NV_stream_sync
      - EGL_NV_stream_consumer_gltexture_yuv
      - EGL_NV_stream_attrib
      - EGL_NV_sync
      - EGL_NV_system_time
      - EGL_NV_output_drm_flip_event
  gles2:
    vendor: NVIDIA Corporation
    vendor: OpenGL ES 3.2 NVIDIA 390.77
    extensions:
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clear_texture
      - GL_EXT_clip_control
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_color_buffer_half_float
      - GL_EXT_conservative_depth
      - GL_EXT_copy_image
      - GL_EXT_debug_label
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_float_blend
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_indirect
      - GL_EXT_multisample_compatibility
      - GL_EXT_multisampled_render_to_texture
      - GL_EXT_multisampled_render_to_texture2
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_post_depth_coverage
      - GL_EXT_primitive_bounding_box
      - GL_EXT_raster_multisample
      - GL_EXT_render_snorm
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_non_constant_global_initializers
      - GL_EXT_shader_texture_lod
      - GL_EXT_shadow_samplers
      - GL_EXT_sparse_texture
      - GL_EXT_sparse_texture2
      - GL_EXT_sRGB
      - GL_EXT_sRGB_write_control
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_bptc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_filter_minmax
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_mirror_clamp_to_edge
      - GL_EXT_texture_norm16
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_storage
      - GL_EXT_texture_view
      - GL_EXT_draw_transform_feedback
      - GL_EXT_unpack_subimage
      - GL_EXT_window_rectangles
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_KHR_parallel_shader_compile
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_NV_bgr
      - GL_NV_bindless_texture
      - GL_NV_blend_equation_advanced
      - GL_NV_blend_equation_advanced_coherent
      - GL_NVX_blend_equation_advanced_multi_draw_buffers
      - GL_NV_blend_minmax_factor
      - GL_NV_clip_space_w_scaling
      - GL_NV_conditional_render
      - GL_NV_conservative_raster
      - GL_NV_conservative_raster_pre_snap_triangles
      - GL_NV_copy_buffer
      - GL_NV_copy_image
      - GL_NV_draw_buffers
      - GL_NV_draw_instanced
      - GL_NV_draw_texture
      - GL_NV_draw_vulkan_image
      - GL_NV_EGL_stream_consumer_external
      - GL_NV_explicit_attrib_location
      - GL_NV_fbo_color_attachments
      - GL_NV_fill_rectangle
      - GL_NV_fragment_coverage_to_color
      - GL_NV_fragment_shader_interlock
      - GL_NV_framebuffer_blit
      - GL_NV_framebuffer_mixed_samples
      - GL_NV_framebuffer_multisample
      - GL_NV_generate_mipmap_sRGB
      - GL_NV_geometry_shader_passthrough
      - GL_NV_instanced_arrays
      - GL_NV_internalformat_sample_query
      - GL_NV_gpu_shader5
      - GL_NV_image_formats
      - GL_NV_occlusion_query_samples
      - GL_NV_non_square_matrices
      - GL_NV_pack_subimage
      - GL_NV_packed_float
      - GL_NV_packed_float_linear
      - GL_NV_path_rendering
      - GL_NV_path_rendering_shared_edge
      - GL_NV_pixel_buffer_object
      - GL_NV_polygon_mode
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_NV_sample_locations
      - GL_NV_sample_mask_override_coverage
      - GL_NV_shader_atomic_fp16_vector
      - GL_NV_shader_noperspective_interpolation
      - GL_NV_shadow_samplers_array
      - GL_NV_shadow_samplers_cube
      - GL_NV_sRGB_formats
      - GL_NV_stereo_view_rendering
      - GL_NV_texture_array
      - GL_NV_texture_barrier
      - GL_NV_texture_border_clamp
      - GL_NV_texture_compression_latc
      - GL_NV_texture_compression_s3tc
      - GL_NV_texture_compression_s3tc_update
      - GL_NV_timer_query
      - GL_NV_viewport_array
      - GL_NV_viewport_array2
      - GL_NV_viewport_swizzle
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_OES_depth24
      - GL_OES_depth32
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_texture_border_clamp
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_buffer
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_gpu_shader5
      - GL_OES_shader_io_blocks
      - GL_OES_texture_view
      - GL_OES_primitive_bounding_box
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_image_external_essl3
      - GL_OES_EGL_sync
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_surfaceless_context
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_npot
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
      - GL_ANDROID_extension_pack_es31a

**Comment by parithy** [comment]
Log cat: 
12-18 06:30:47.194   115   361 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.snapchat.android cmp=com.snapchat.android/.LandingPageActivityV1} from uid 10083 on display 0
12-18 06:30:47.203  2805  2816 I art     : Background sticky concurrent mark sweep GC freed 3418(379KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 4MB/5MB, paused 5.702ms total 11.109ms
12-18 06:30:47.396  2805  2825 I art     : Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.JobIntentService$f>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
12-18 06:30:47.396  2805  2825 I art     :   at void com.snapchat.android.service.SnapchatService.b(android.content.Context, android.content.Intent) (SourceFile:28)
12-18 06:30:47.396  2805  2825 I art     :   at int axli.a(android.content.Context, android.content.Intent) (SourceFile:583)
12-18 06:30:47.396  2805  2825 I art     :   at void asna$6.run() (SourceFile:8517)
12-18 06:30:47.396  2805  2825 I art     :   at void acsu.run() (SourceFile:75)
12-18 06:30:47.396  2805  2825 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
12-18 06:30:47.396  2805  2825 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
12-18 06:30:47.396  2805  2825 I art     :   at void actr$3$1.run() (SourceFile:319)
12-18 06:30:47.396  2805  2825 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.job.JobServiceEngine" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.snapchat.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.snapchat.android-1/lib/arm, /data/app/com.snapchat.android-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-18 06:30:47.396  2805  2825 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
12-18 06:30:47.396  2805  2825 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
12-18 06:30:47.436  2805  2816 W art     : Suspending all threads took: 5.617ms
12-18 06:30:47.443  2805  2816 I art     : Background partial concurrent mark sweep GC freed 3077(264KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 5MB/9MB, paused 10.472ms total 40.552ms
12-18 06:30:47.555  2805  2825 D ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.android.gms-2/lib/x86:/data/app/com.google.android.gms-2/base.apk!/lib/x86 for namespace 0xf7bf1090
12-18 06:30:47.595  2805  2842 E AndroidRuntime: FATAL EXCEPTION: ScDownloadManager-Thread-1
12-18 06:30:47.595  2805  2842 E AndroidRuntime: Process: com.snapchat.android, PID: 2805
12-18 06:30:47.595  2805  2842 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.snapchat.android-1/lib/arm/libcronet.69.0.3497.100.so" has unexpected e_machine: 40
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1530)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at org.chromium.net.impl.CronetLibraryLoader.a(SourceFile:65)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at org.chromium.net.impl.CronetUrlRequestContext.<init>(SourceFile:154)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at bhjg.b(SourceFile:32)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at bhio$a.c(SourceFile:231)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at afhc$a.b(SourceFile:408)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at afhc$a.a(SourceFile:341)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at awdc.get(SourceFile:30)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at afhc.a(SourceFile:12273)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:253)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avci.a(SourceFile:29)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcl.a(SourceFile:38)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avct.a(SourceFile:49)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcs.a(SourceFile:20)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcp.a(SourceFile:46)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avco.a(SourceFile:37)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcn.a(SourceFile:69)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcr.a(SourceFile:62)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcq.a(SourceFile:69)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avdv.a(SourceFile:58)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcj.a(SourceFile:25)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbx.a(SourceFile:35)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avck.a(SourceFile:49)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avcm.a(SourceFile:39)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn$a.a(SourceFile:211)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbn.a(SourceFile:156)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avbi.executeSynchronously(SourceFile:285)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avdw.a(SourceFile:262)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avdw$2.run(SourceFile:1225)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
12-18 06:30:47.595  2805  2842 E AndroidRuntime:        at avxw.run(SourceFile:21)
12-18 06:30:47.611   115   872 W ActivityManager:   Force finishing activity com.snapchat.android/.LandingPageActivityV1
12-18 06:30:47.613   115   872 W ActivityManager:   Force finishing activity org.anbox.appmgr/.AppViewActivity
12-18 06:30:47.627   115   863 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@1f1ab00 (uid=10000 pid=404)
12-18

**Comment by parithy** [comment]
i think this bug is taken care of in the latest release in edge

**Comment by okadath** [comment]
the same happens to me but with instagram and tiktok, other apps (facebook, snapchat) run without any problem

**Comment by baptx** [comment]
The issue is still here for me, Snapchat crashes Anbox when I start it. I downloaded the latest APK file from https://apps.evozi.com/apk-downloader/ because Snapchat was not displayed in the Google Play Store with the script https://github.com/geeks-r-us/anbox-playstore-installer (maybe the issue is related).

**Comment by 4015-dev** [comment]
I have the same issue, on ubuntu 20.04

**Comment by baptx** [comment]
On https://forum.xda-developers.com/t/snapchat-root-check-bypass.4156957/ I read people where able to bypass SafetyNet protection from Snapchat with a tool called MagiskHide.

But on https://forum.xda-developers.com/t/installing-magisk-on-an-emulator.3648413/ I read this for Android x86 (which could be similar for Anbox as well):
"No, you cannot pass SafetyNet because it's a debug build (Android x86, probably emulator also don't have proper fingerprint, etc...). You must fake a real device that was certified by Google to pass SafetyNet, and probably you'd also need a newer version of Magisk since Google patched the SafetyNet trick that Magisk used prior to v14.0 by what I've read..."

I also read this in the link above which seems complicated but maybe someone will have time to try:
"I was able to install Magisk V12.0 on Android x86 7.1.2 rc2, using this tools to create a "fake" boot.img using kernel and ramdisk.img files:
https://forum.xda-developers.com/showthread.php?t=2319018

But I had to make small modifications in the install scripts and magic_mask.sh to bypass some errors and correctly mount system to the magisk folder. Newer versions don't have magic_mask.sh anymore but a binary, so unless you modify the source and compile it yourself I think it won't work. Probably because v12.0 is somewhat old I can't install modules automatically using Magisk Manager tho..."

**Comment by baptx** [comment]
Good news: yesterday I was able to log in and use Snapchat from Anbox. It was the first time I managed to log in since I don't use an Android smartphone. I used Anbox edge version on Debian. Before it worked, I tried with Android x86 (64 bit version 9.0 r2) on VirtualBox but there was an infinite loading loop.
Since this year, there is even a web version for Snapchat but it requires to have installed the mobile app. Firefox is not officially supported but it is possible to change the user agent to latest Linux Chromium with an addon like https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher-revived/ (some user agent switcher addons did not work for Snapchat).
However it looks like we need to use the mobile app to start a conversation with someone new.

In case you cannot log in, it could be a device ban, some people even have to buy a new phone to log in:
https://www.reddit.com/r/SnapchatHelp/comments/y7zddt/snapchat_device_ban_work_around/
I found this information to change the IMEI in Anbox but never tried (maybe Snapchat is checking the MAC address also):
https://android.stackexchange.com/questions/245329/anbox-imei-change-device-spoofing
https://github.com/anbox/anbox/issues/155
https://github.com/anbox/anbox/issues/1759
